card_data:
  language: "en"
  license: "cc-by-nc-4.0"
model_description: "A finetune of Yolo5 intended for identifying beach trash."
developers: "Jeffrey Queisser, Christopher Buckley"
funded_by: "Okinawa Institute of Science and Technology COI Next Grant"
model_type: "Yolo5"
license: "CC BY-NC 4.0"
base_model: "Yolo5"
repo: "https://github.com/okinawa-ai-beach-robot/yolo5_beachbot"
model_id: "yolo5_beachbot"
training_data: "https://universe.roboflow.com/okinawaaibeachrobot/beach-cleaning-object-detection/dataset/1"
preprocessing: "{'preprocessing': {'auto-orient': True, 'resize': {'width': 1280, 'height': 800, 'format': 'Fill (with center crop) in'}}}\nSee https://docs.roboflow.com/api-reference/versions/create-a-project-version for more information"
training_regime: "TODO populate with any hyperparameters"
testing_data: "https://universe.roboflow.com/okinawaaibeachrobot/beach-cleaning-object-detection/dataset/1/images?split=test"
bias_risks_limitations: "Note the dataset is small and test set can have quite similar images to the train set. \nThis was an early version of the dataset so results are not reliable"
bias_recommendations: "Use later version of the dataset"
testing_metrics: "TODO populate with any metrics\ne.g. loss function"
results: "TODO populate with any results"
results_summary: "TODO"
model_card_authors: "Christopher Buckley"
model_card_contact: "https://github.com/okinawa-ai-beach-robot/home/discussions"
